name: cae-lo
channels:
- anaconda
- conda-forge
- rapidsai
- defaults
dependencies:
- matplotlib=3.1.3
- numpy=1.18.1
- mayavi=4.7.1
- tensorflow-gpu=1.14
- Keras=2.3.1
- scipy=1.5.0
- cupy=7.8.0
- Pillow=7.2.0
- scikit-learn=0.23.2
